### ISSUE TITLE
Support Dart 2.0 / 2.1

### ISSUE THREAD

**Issue by sturmf** [alexeieleusis/greencat#23]
I am using greencat in an older application which I currently try to port to Dart 2.1. Unfortunately greencat is not yet compatible with Dart >=2.0.0

Are there any plans on support, or maybe already work on it?

**Comment by alexeieleusis** [comment]
Hi Fabian,

It's been a while since I last worked on greencat and stopped using it. I
remember the code was strong mode compliant, which means it should work on
newer versions of dart. Have you tried directly downloading the code? Even
if there are errors, they should be easy to fix.

I can look into it definitely, but I don't think I'll have time before Jan
15th.

**Comment by alexeieleusis** [comment]
I just published a Dart 2 compliant version to pub. Enjoy!

**Comment by sturmf** [comment]
Hey great thanks! Just for your info, I now almost ported my code (still struggling with the tests) and so far I used an override for greencat and it worked without changes in your lib.

**Comment by alexeieleusis** [comment]
Testing async code is challenging, good luck!
